djcode/IMS/urls.py
__author__ = 'Adward'

"""djcode URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from IMS import views, profile, course_views, user_views, log_views, forget_pwd

urlpatterns = [
    url(r'^login/$', views.loggingin), #by adward
    #url(r'^hello/', views.startup),
    url(r'^add_user/', views.add_user), #by adward
    url(r'^user_added/', views.user_added), #by adward
    url(r'^user_auth/', views.user_auth), #by adward
    url(r'^home/$', views.home), #by adward
    url(r'^logout/$', views.loggingout), #by adward
    url(r'^home/profile/$', profile.profile), #by adward
    url(r'^home/profile/changeUserInfo/$', profile.changeUserInfo), #by xyh
    url(r'^home/profile/changePasswd/$', profile.changePasswd), #by xyh
    url(r'^home/profile/changePhoto/$', profile.changePhoto), #by xyh
    url(r'^log/$', log_views.all_log), # by xyh
    url(r'^log/deleteLog/$', log_views.delete_all_log), # by xyh
    url(r'^course/$', course_views.courseMain), #by saltless
    url(r'^course/add/$', course_views.courseAdd), #by saltless
    url(r'^course/delete/$', course_views.courseDelete), #by saltless
    url(r'^course/modify/$', course_views.courseModify), #by saltless
    url(r'^user/$', user_views.userMain), #by Henry
    url(r'^user/add_faculty/$', user_views.facultyAdd), #by Henry
    url(r'^user/delete_faculty/$', user_views.facultyDelete), #by Henry
    url(r'^user/modify_faculty/$', user_views.facultyModify), #by Henry
    url(r'^user/add_student/$', user_views.studentAdd), #by Henry
    url(r'^user/delete_student/$', user_views.studentDelete), #by Henry
    url(r'^user/modify_student/$', user_views.studentModify), #by Henry
    url(r'^user/add_admin/$', user_views.adminAdd), #by Henry
    url(r'^user/delete_admin/$', user_views.adminDelete), #by Henry
    url(r'^user/modify_admin/$', user_views.adminModify), #by Henry
    url(r'^forget_pwd/$', forget_pwd.forget_pwd), #by adward
    url(r'^reset_pwd_mail/$', forget_pwd.reset_pwd_mail), #by adward
    url(r'^reset_pwd/(?P<key>[0-9a-zA-Z]{20})/$', forget_pwd.reset_pwd), #by adward
]

## For upload user photos
urlpatterns += static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djcode/IMS/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.

#class Login_info: handled by Django User
import os
from django.conf import settings
DEFAULT_PHOTO_DIR = os.path.join("photo", "default.jpg")


def get_photo_file_name(instance, filename):
    # print instance.id
    # print filename
    filename = filename.encode('utf-8')
    newFilename = os.path.join("photo", str(instance.id)) + "." + str(filename).split('.')[-1]
    newFullFilename = os.path.join(settings.MEDIA_ROOT, newFilename)
    if os.path.exists(newFullFilename):
        os.remove(newFullFilename)
    return newFilename

class Student_user(models.Model):
    '''
    | id | contact | name | gender | college | major | grade | gpa | credits |
    |---|---|---|---|---|---|---|---|---|
    | CHARACTER(10) | VARCHAR(11) | VARCHAR(20) | BOOLEAN | VARCHAR(50) | VARCHAR(50) | INTEGER | FLOAT | FLOAT |
    '''
    id = models.CharField(max_length=10, primary_key=True)
    contact = models.CharField(max_length=11,default='18812345678')
    name = models.CharField(max_length=20,default='张三')
    gender = models.BooleanField(default=True)
    college = models.CharField(max_length=50,default='计算机科学与技术学院')
    major = models.CharField(max_length=50,default='计算机科学与技术')
    grade = models.IntegerField(default=3)
    gpa = models.FloatField(default=4.0)
    credits = models.FloatField(default=100.0)
    isSpecial = models.BooleanField(default=False)
    photo = models.FileField(upload_to=get_photo_file_name, default=DEFAULT_PHOTO_DIR)

    def __unicode__(self):
        return u'id:%s, contact:%s, name:%s, gender:%d, college:%s, major:%s, grade:%s, gpa:%f, credits:%f'%(self.id, self.contact,self.name,self.gender, self.college,self.major,self.grade, self.gpa, self.credits)
        # return 'id:' + self.id

    def __str__(self):
        return self.name

    class Meta:
        permissions = (
            ("student_manage", "Can manage stu user info"),
        )


class Faculty_user(models.Model):
    '''
    | id | contact | name | gender | college | major | degree | title |
    |---|---|---|---|---|---|---|---|
    | CHARACTER(6) | VARCHAR(11) | VARCHAR(20) | BOOLEAN | VARCHAR(50) | VARCHAR(50) | VARCHAR(20) | VARCHAR(20) |
    '''
    id = models.CharField(max_length=6, primary_key=True)
    contact = models.CharField(max_length=11, default= "18812345678")
    name = models.CharField(max_length=20,default= "张三")
    gender = models.BooleanField(default=0)
    college = models.CharField(max_length=50,default="计算机科学与技术学院")
    major = models.CharField(max_length=50,default='计算机科学与技术')
    degree = models.CharField(max_length=20,default='博士')
    title = models.CharField(max_length=20, default="研究员")
    isSpecial = models.BooleanField(default=False)
    photo = models.FileField(upload_to=get_photo_file_name, default=DEFAULT_PHOTO_DIR)

    def __unicode__(self):
        return u'id:%s, contact:%s, name:%s, gender:%d, college:%s, major:%s, degree:%s, title:%s'%(self.id, self.contact,self.name,self.gender, self.college,self.major,self.degree, self.title)
        # return 'id:' + self.id

    def __str__(self):
        return self.name

    class Meta:
        permissions = (
            ("faculty_manage", "Can manage faculty user info"),
        )

class Admin_user(models.Model):
    '''
    | id | contact | name | gender | college |
    |---|---|---|---|---|
    | CHARACTER(3) | VARCHAR(11) | VARCHAR(20) | BOOLEAN | VARCHAR(50) |
    '''
    id = models.CharField(max_length=3, primary_key=True)
    contact = models.CharField(max_length=11,default="18812345678")
    name = models.CharField(max_length=20, default="张三")
    gender = models.BooleanField(default=0)
    college = models.CharField(max_length=50, default="all") #default for superadmin
    photo = models.FileField(upload_to=get_photo_file_name, default=DEFAULT_PHOTO_DIR)

    def __unicode__(self):
        return u'id:%s, contact:%s, name:%s, gender:%d, college:%s'%(self.id, self.contact,self.name,self.gender, self.college)
        # return 'id:' + self.id

    def __str__(self):
        return self.name

    class Meta:
        permissions = (
            ("admin_manage", "Can manage admin user info"),
        )

class Course_info(models.Model):
    '''
    | course_id | name | credits | semester | textbook | college |
    |---|---|---|---|---|---|
    | CHARACTER(8) | VARCHAR(110) | FLOAT | INTEGER | VARCHAR(110) | VARCHAR(50) |
    '''
    course_id = models.CharField(max_length=8, primary_key=True)
    name = models.CharField(max_length=110)
    credits = models.FloatField(default=0)
    semester = models.IntegerField(default=0)
    textbook = models.CharField(max_length=110)
    college = models.CharField(max_length=50)
    course_type = models.IntegerField(default=0) #必修、选项和通识，根据选课组要求加入

    def __unicode__(self):
        return u'course_id:%s, name:%s, credits:%f, semester:%d, textbook:%s, college:%s, course_type:%d'%(self.course_id, self.name, self.credits, self.semester, self.textbook, self.college, self.course_type)

    def __str__(self):
        return self.name

    class Meta:
        permissions = (
            ("course_manage", "Can manage basic course info"),
        )

class Class_info(models.Model):
    '''
    | class_id | course_id | teacher | time | room | examdate | examtime | examroom | capacity |
    |---|---|---|---|---|---|---|---|---|
    | CHARACTER(10) | CHARACTER(8) | VARCHAR(20) | INTEGER | VARCHAR(20) | DATETIME(TEXT) | INTEGER | VARCHAR(20) | INTEGER |
    '''
    class_id = models.CharField(max_length=10)
    course_id = models.ForeignKey(Course_info)
    teacher = models.CharField(max_length=20)
    time = models.IntegerField(default=0)
    room = models.CharField(max_length=20)
    examdate = models.DateTimeField
    examtime = models.IntegerField(default=0)
    examroom = models.CharField(max_length=20)
    capacity = models.IntegerField(default=0)
    semester = models.IntegerField(default=0) #开课学期
    remain = models.IntegerField(default=0) #选课剩余容量
    year = models.IntegerField(default=2015) #年份（学年）
    language = models.IntegerField(default=0) #中文、英文、双语

    def __unicode__(self):
        return u'class_id:%s, teacher:%s, time:%d, room:%s, examdate:%s, examtime:%d, examroom:%s, capacity:%d, semester:%d, remain:%d, year:%d, language:%d'%(self.class_id, self.teacher, self.time, self.room, self.examdate, self.examtime, self.examroom, self.capacity, self.semester, self.remain, self.year, self.language)

    def __str__(self):
        return self.id

'''
class Pre_requisites(models.Model):
    course_id = models.CharField(max_length=8)
    prereq = models.CharField(max_length=8)
'''

class Class_table(models.Model):
    '''
    | student_id | class_id |
    |---|---|
    | CHARACTER(10) | CHARACTER(10) |
    '''
    student_id = models.ForeignKey(Student_user)
    class_id = models.ForeignKey(Class_info)

'''
class Sys_log(models.Model):
    time = models.CharField(max_length=20)
    optype = models.CharField(max_length=20, default='update')
    table = models.CharField(max_length=20)
    primkey = models.CharField(max_length=20)
    field = models.CharField(max_length=20)
    pre = models.CharField(max_length=50, default='none')
    post = models.CharField(max_length=50, default='none')
'''

class FindPass(models.Model):
    username = models.CharField(max_length=20)
    activation_key = models.CharField(max_length=20)
    timestamp = models.CharField(max_length=10) #int part
    #date = models.DateField(auto_now_add=True)

djcode/IMS/templates/AccessFault.html
<!-- by xyh-->

<!DOCTYPE html>
<html>
<head>
	<title>Access Prohibited</title>
</head>
<body>
	<h1>Access Prohibited.</h1>
	<p></p>
	<p>Please check your login status.</p>
	<a href="/ims/home/">back to homepage</a>
</body>
</html>

djcode/IMS/templates/AddCourse.html
<!-- #by henry -->

<html>

<style type="text/css">
    ul.errorlist {
        margin: 0;
        padding: 0;
    }
    .errorlist li {
        background-color: red;
        color: white;
        display: block;
        font-size: 10px;
        margin: 0 0 3px;
        padding: 4px 5px;
    }

    .input-group {
        margin-top: 15px;
    }
    .btn {
        margin-top: 15px;
    }
    .alert {
        width: 50%;
    }

</style>

<head>
    <title>Add course</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
</head>
<body>
<br/>
<div class="container">
    <nav class="navbar" role="navigation">
        <div>
            <ul class="nav nav-tabs navbar-left">
                <li role="presentation"><a href="/ims/home/">个人首页</a></li>
                <li role="presentation" class="active"><a href="/ims/course/">课程信息管理</a></li>
                <li role="presentation"><a href="/ims/user/">用户信息管理</a></li>
                <li role="presentation"><a href="/ims/home/profile/">个人信息管理</a></li>
                <li role="presentation"><a href="/ims/logout/">退出登录</a></li>
            </ul>
            <ul class="nav navbar-right">

            </ul>
        </div>
    </nav>

    <div class="page-header">
        <h1>New Course Information</h1>
    </div>

    {% if addIsDone %}
        <div class="alert alert-success">
            Course added successfully.
        </div>
    {% endif %}

    {% if form.errors %}
        <div class="alert alert-warning">
            Please correct the error{{ form.errors|pluralize }} below.
        </div>
    {% endif %}

    <div class="form-group" style="width: 50%">
        <form id="submit_single" action="" method="post" enctype="multipart/form-data">
            {% if facultyAdd %}
                <p>Adding courses into {{ userCollege }} college.</p>
            {% endif %}
            {% csrf_token %}

            <input type="submit" value="Add This Course" class="btn btn-default">
        </form>

        <form id="submit_csv" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="submit" value="Add Courses from CSV" class="btn btn-default">
            <br/><br/>
            <input type="file" name="file" value="Upload" role="button">
        </form>
    </div>
    {% if multiAdd %}
        <form id='multiAdd' action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="alert alert-info">
                <p>Sure to add following courses?</p>
            </div>
            <table class="table table-striped table-hover">
                <tr>
                    <th>Course ID</th>
                    <th>Course Name</th>
                    <th>Credits</th>
                    <th>Semester</th>
                    <th>Textbook</th>
                    <th>College</th>
                    <th>Type</th>
                </tr>
                {% for term in terms %}
                    <tr>
                        <th>{{ term.0 }}</th>
                        <th>{{ term.1 }}</th>
                        <th>{{ term.2 }}</th>
                        <th>{{ term.3 }}</th>
                        <th>{{ term.4 }}</th>
                        <th>{{ term.5 }}</th>
                        <th>{{ term.6 }}</th>
                    </tr>
                {% endfor %}
            </table>
            <input type="button" name="multiAddConform" value="Confirm" class="btn btn-info" onclick="javascript:f('multiAdd')">
            <input type="submit" name="multiAddCancle" value="Cancel" class="btn btn-default">
            <input type="hidden" name="file">
        </form>
    {% endif %}

    {% if errorExist %}
        <div class="alert alert-danger">
            The followings were not successfully added.
        </div>
        <table class="table table-striped table-hover">
            <tr>
                <th>FAULT</th>
                <th>Course ID</th>
                <th>Course Name</th>
                <th>Credits</th>
                <th>Semester</th>
                <th>Textbook</th>
                <th>College</th>
                <th>Type</th>
            </tr>
            {% for term in errorImport %}
                <tr>
                    <th>{{ term.7 }}</th>
                    <th>{{ term.0 }}</th>
                    <th>{{ term.1 }}</th>
                    <th>{{ term.2 }}</th>
                    <th>{{ term.3 }}</th>
                    <th>{{ term.4 }}</th>
                    <th>{{ term.5 }}</th>
                    <th>{{ term.6 }}</th>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
</div>
</body>
</html>

<script type="text/javascript">
    function f(a) {
        var tables = document.getElementsByTagName("th");
        var form = document.getElementById(a);
        var s = "";
        for (var i = 7; i < tables.length; i ++) {
            s += tables[i].innerText + ",";
        };
        form.file.value = s;
        form.submit();
    }

    {% for field in form %}
        var input_group = $("<div class='input-group {% if field.errors %}has-error{% endif %}'></div>");
        var span = $("<span class='input-group-addon'> {{ field.label }} </span>");
        var field_body = $('{{ field }}');
        field_body.attr({"class": "form-control", "required": ""});
        input_group.append(span).append(field_body);
        $("#submit_single").append(input_group);
    {% endfor %}

</script>

djcode/IMS/templates/AddFaculty.html
<!-- #by henry -->

<!DOCTYPE html>
<html>

<style type="text/css">
    ul.errorlist {
        margin: 0;
        padding: 0;
    }
    .errorlist li {
        background-color: red;
        color: white;
        display: block;
        font-size: 10px;
        margin: 0 0 3px;
        padding: 4px 5px;
    }

    .input-group {
        margin-top: 15px;
    }
    .btn {
        margin-top: 15px;
    }
    .alert {
        width: 50%;
    }
</style>

<head lang="en">
    <meta charset="UTF-8">
    <title>Add faculty</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
</head>
<body>
<br/>
<div class="container">
    <nav class="navbar" role="navigation">
        <div>
            <ul class="nav nav-tabs navbar-left">
                <li role="presentation"><a href="/ims/home/">个人首页</a></li>
                <li role="presentation"><a href="/ims/course/">课程信息管理</a></li>
                <li role="presentation" class="active"><a href="/ims/user/">用户信息管理</a></li>
                <li role="presentation"><a href="/ims/home/profile/">个人信息管理</a></li>
                <li role="presentation"><a href="/ims/logout/">退出登录</a></li>
            </ul>
            <ul class="nav navbar-right">

            </ul>
        </div>
    </nav>

    <div class="page-header">
        <h1>New Faculty Infomation</h1>
    </div>

    {% if addIsDone %}
        <div class="alert alert-success">
            Faculties added successfully.
        </div>
    {% endif %}

    {% if form.errors %}
        <div class="alert alert-warning">
            Please correct the error{{ form.errors|pluralize }} below.
        </div>
    {% endif %}

    <div class="form-group" style="width: 50%;">
        <form id="submit_single" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="submit" value="Add This Faculty" class="btn btn-default">
            <br/><br/>
            <input type="checkbox" id="id_isSpecial" name="isSpecial" onclick="toggleSpecialStatus()">
            <label for="id_isSpecial"> Is Special? </label>

            <div class="btn-group" data-toggle="buttons" id="authority">
                <button class="btn btn-default" id="au1" disabled="disabled">
                    <input type="checkbox" id="id_canManageCourses" name="canManageCourses"> Can Manage Courses
                </button>
                <button class="btn btn-default" id="au2" disabled="disabled">
                    <input type="checkbox" id="id_canManageStudents" name="canManageStudents"> Can Manage Students
                </button>
                <button class="btn btn-default" id="au3" disabled="disabled">
                    <input type="checkbox" id="id_canManageFaculties" name="canManageFaculties"> Can Manage Faculties
                </button>
            </div>
        </form>

        <form id="submit_csv" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="submit" value="Add Faculties from CSV" class="btn btn-default">
            <br/><br/>
            <input type="file" name="file" value="Upload" role="button">
        </form>
    </div>

    {% if multiAdd %}
        <form id='multiAdd' action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="alert alert-info">
                Sure to add following faculties?
            </div>
            <table class="table table-striped table-hover">
                <tr>
                    <th>Id</th>
                    <th>Contact</th>
                    <th>Name</th>
                    <th>Gender</th>
                    <th>College</th>
                    <th>Major</th>
                    <th>Degree</th>
                    <th>Title</th>
                    <th>IsSpecial</th>
                </tr>
                {% for term in terms %}
                    <tr>
                        <th>{{ term.0 }}</th>
                        <th>{{ term.1 }}</th>
                        <th>{{ term.2 }}</th>
                        <th>{{ term.3 }}</th>
                        <th>{{ term.4 }}</th>
                        <th>{{ term.5 }}</th>
                        <th>{{ term.6 }}</th>
                        <th>{{ term.7 }}</th>
                        <th>{{ term.8 }}</th>
                    </tr>
                {% endfor %}
            </table>
            <input type="button" name="multiAddConfirm" value="Confirm" class="btn btn-info" onclick="javascript:f('multiAdd')">
            <input type="submit" name="multiAddCancel" value="Cancel" class="btn btn-default">
            <input type="hidden" name="file">
        </form>
    {% endif %}

    {% if errorExist %}
        <div class="alert alert-danger">
            The followings were not successfully added.
        </div>
        <table class="table table-striped table-hover">
            <tr>
                <th>FAULT</th>
                <th>ID</th>
                <th>Contact</th>
                <th>Name</th>
                <th>Gender</th>
                <th>College</th>
                <th>Major</th>
                <th>Degree</th>
                <th>Title</th>
            </tr>
        {% for term in existed %}
            <tr>
                <th>{{ term.8 }}</th>
                <th>{{ term.0 }}</th>
                <th>{{ term.1 }}</th>
                <th>{{ term.2 }}</th>
                <th>{{ term.3 }}</th>
                <th>{{ term.4 }}</th>
                <th>{{ term.5 }}</th>
                <th>{{ term.6 }}</th>
                <th>{{ term.7 }}</th>
            </tr>
        {% endfor %}
        </table>
    {% endif %}
</body>
</html>

<script type="text/javascript">
    var isSpecial = false;

    function f(a) {
        var tables = document.getElementsByTagName("th");
        var form = document.getElementById(a);
        var s = "";
        for (var i = 8; i < tables.length; i ++) {
            s += tables[i].innerText + ",";
        };
        form.file.value = s;
        form.submit();
    }

    {% for field in form %}
        var label = "{{ field.label }}";
        if (label=="Isspecial" || label=="Canmanagecourses"
                || label=="Canmanagestudents" || label=="Canmanagefaculties" || label=="Photo") {

        }
        else {
            var input_group = $("<div class='input-group {% if field.errors %}has-error{% endif %}'></div>");
            var span = $("<span class='input-group-addon'> {{ field.label }} </span>");
            var field_body = $('{{ field }}');
            field_body.attr({"class": "form-control", "required": ""});
            input_group.append(span).append(field_body);
            $("#submit_single").append(input_group);
        }
    {% endfor %}

    {% if not isSuper %}
        $("#id_college").attr("readonly", "");
    {% endif %}

    function toggleSpecialStatus() {
        if (isSpecial) {
            $("#au1").attr("disabled", "");
            $("#au2").attr("disabled", "");
            $("#au3").attr("disabled", "");
            isSpecial = false;
        }
        else {
            $("#au1").removeAttr("disabled");
            $("#au2").removeAttr("disabled");
            $("#au3").removeAttr("disabled");
            isSpecial = true;
        }
    }
</script>
</html>

djcode/IMS/templates/ModifyStudent.html
<!-- #by henry -->

<!DOCTYPE html>
<html>
<head lang="en">
    <title>Modify Student</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <style>
        .form-group {
            padding: 1%;
        }
    </style>
</head>
<body>
<br>
<div class="container">
    <nav class="navbar" role="navigation">
        <div>
            <ul class="nav nav-tabs navbar-left">
                <li role="presentation"><a href="/ims/home/">个人首页</a></li>
                <li role="presentation"><a href="/ims/course/">课程信息管理</a></li>
                <li role="presentation"  class="active"><a href="/ims/user/">用户信息管理</a></li>
                <li role="presentation"><a href="/ims/home/profile/">个人信息管理</a></li>
                <li role="presentation"><a href="/ims/logout/">退出登录</a></li>
            </ul>
            <ul class="nav navbar-right">

            </ul>
        </div>
    </nav>

    <div class="page-header">
        <h1>Search Students For Modification</h1>
    </div>

    {% if errors %}
        <ul>
            {% for error in errors %}
                <p style="color: red">{{ error }}</p>
            {% endfor %}
        </ul>
    {% endif %}


    <form id='formSearch' action="" method="post" class="form-inline">
        {% csrf_token %}
        <div class="form-group">
            <label for="key" class="sr-only"></label>
            <input id="key" type="text" name="term" class="form-control">
        </div>
        <div class="form-group">
            <label for="type" class="sr-only"></label>
            <select id="type" name="type" class="form-control">
                <option value ="id">ID</option>
                <option value ="name">Name</option>
            </select>
        </div>
        <div class="form-group">
            <input type="submit" value="Search Student" class="form-control">
        </div>
    </form>

    {% if modifyIsDone %}
        <p style="color: blue;">
            Student Modified successfully.
        </p>
    {% endif %}

    {% if inModify %}
        <form id="submit" action="" method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Submit">
            <!--<input type="hidden" name = "studentId" value={{ studentId }}>-->
        </form>
    {% else %}
        <form id='formSelect' action="" method="post">
            {% csrf_token %}
            {% if students %}
                <br/>
                <div class="alert alert-success">
                    Found {{ students | length }} students{{ students | pluralize }}.
                </div>
                <table class="table table-striped table-hover">
                    <tr>
                        <th>ID</th>
                        <th>Contact</th>
                        <th>Name</th>
                        <th>Gender</th>
                        <th>College</th>
                        <th>Major</th>
                        <th>Grade</th>
                        <th>Gpa</th>
                        <th>Credits</th>
                    </tr>
                    {% for student in students %}
                        <tr>
                            <th>{{ student.id }}</th>
                            <th>{{ student.contact }}</th>
                            <th>{{ student.name }}</th>
                            <th>{{ student.gender }}</th>
                            <th>{{ student.college }}</th>
                            <th>{{ student.major }}</th>
                            <th>{{ student.grade }}</th>
                            <th>{{ student.gpa }}</th>
                            <th>{{ student.credits }}</th>
                            <th><input type="button" class="btn btn-info" name="student" value="modify" onclick="javascript:f('{{student.id}}')"></th>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                {% if inSearch %}
                    <br/>
                    <div class="alert alert-warning">
                        No Student Found.
                    </div>
                {% endif %}
            {% endif %}
            <input type="hidden" name="modifyid" id="modifyid">
        </form>
    {% endif %}

</body>
</html>

<script type="text/javascript">
    function f(a) {
        var form = document.getElementById("formSelect");
        form.modifyid.value = a;
        form.submit();
    }
    $("#id_id").attr("readonly", "");
    $("#id_gender").attr("readonly", "");
    $("#id_college").attr("readonly", "");
</script>

djcode/IMS/templates/change_passwd_success.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    修改成功！
    <br/>
    <a href="/">Go Login Again>>></a>

</body>
</html>